"""Slicer auto-detection from G-code comment patterns.

Identifies the slicer that produced a G-code file by matching known
signature comments in the file header (first ~100 lines).

Supported slicers: PrusaSlicer, OrcaSlicer, BambuStudio, Cura.
"""

from __future__ import annotations

import re

# ---------------------------------------------------------------------------
# Pre-compiled patterns (module-level for performance)
# ---------------------------------------------------------------------------
# Each pattern captures an optional version string.
# Order matters at detection time: OrcaSlicer must be checked before
# BambuStudio because OrcaSlicer (a Bambu fork) may emit lines that
# also match the BambuStudio pattern.

_RE_PRUSASLICER = re.compile(r";\s*generated by PrusaSlicer\s*([\d.]+)?", re.IGNORECASE)

_RE_ORCASLICER = re.compile(r";\s*generated by OrcaSlicer\s*([\d.]+)?", re.IGNORECASE)

_RE_BAMBUSTUDIO = re.compile(r";\s*(?:generated by\s+)?BambuStudio\s*([\d.]+)?", re.IGNORECASE)

_RE_CURA_ENGINE = re.compile(r";\s*Generated with Cura_SteamEngine\s*([\d.]+)?", re.IGNORECASE)

_RE_CURA_FLAVOR = re.compile(r";FLAVOR:(?:Marlin|Griffin)", re.IGNORECASE)

# Ordered check list.  Each entry is (pattern, name-prefix, version-in-match).
# ``version_in_match`` is True when the regex has a capture group for version.
_CHECKS: list[tuple[re.Pattern[str], str, bool]] = [
    (_RE_PRUSASLICER, "PrusaSlicer", True),
    (_RE_ORCASLICER, "OrcaSlicer", True),
    (_RE_BAMBUSTUDIO, "BambuStudio", True),
    (_RE_CURA_ENGINE, "Cura_SteamEngine", True),
    (_RE_CURA_FLAVOR, "Cura_SteamEngine", False),
]


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def detect_slicer(lines: list[str]) -> str | None:
    """Identify the slicer from G-code header lines.

    Parameters
    ----------
    lines:
        The first ~100 lines of a G-code file.

    Returns
    -------
    str | None
        A string like ``"PrusaSlicer 2.7.1"`` or ``"Cura_SteamEngine"``
        (version included when present in the comment), or ``None`` if
        no known slicer signature is found.
    """
    for line in lines:
        for pattern, name, has_version in _CHECKS:
            m = pattern.search(line)
            if m is not None:
                if has_version and m.group(1):
                    return f"{name} {m.group(1)}"
                return name
    return None


def detect_slicer_from_file(path: str) -> str | None:
    """Read the first 100 lines of *path* and detect the slicer.

    Parameters
    ----------
    path:
        Filesystem path to a G-code file.

    Returns
    -------
    str | None
        Slicer identification string, or ``None``.
    """
    lines: list[str] = []
    with open(path, encoding="utf-8", errors="replace") as fh:
        for i, line in enumerate(fh):
            if i >= 100:
                break
            lines.append(line)
    return detect_slicer(lines)
