"""Integration tests for the G-code parsing and validation pipeline.

Covers two task requirements:
  T010 — parse_gcode() with each slicer fixture
  T017 — validate_gcode() status outcomes and edge cases
"""

from __future__ import annotations

from pathlib import Path

import pytest

from print3d_skill import parse_gcode, route, validate_gcode
from print3d_skill.exceptions import GcodeParseError, UnsupportedFormatError
from print3d_skill.models.validate import GcodeAnalysis, ValidationStatus

# ---------------------------------------------------------------------------
# T010 — parse_gcode() slicer fixture tests
# ---------------------------------------------------------------------------


class TestParsePrusaSlicer:
    """parse_gcode() correctly extracts all parameters from a PrusaSlicer file."""

    def test_returns_gcode_analysis_instance(self, prusaslicer_gcode_path: Path):
        result = parse_gcode(str(prusaslicer_gcode_path))
        assert isinstance(result, GcodeAnalysis)

    def test_slicer_detected_as_prusaslicer(self, prusaslicer_gcode_path: Path):
        result = parse_gcode(str(prusaslicer_gcode_path))
        assert result.slicer is not None
        assert "PrusaSlicer" in result.slicer

    def test_slicer_version_included(self, prusaslicer_gcode_path: Path):
        # Fixture header: "; generated by PrusaSlicer 2.7.1"
        result = parse_gcode(str(prusaslicer_gcode_path))
        assert "2.7.1" in result.slicer

    def test_hotend_temperatures_extracted(self, prusaslicer_gcode_path: Path):
        result = parse_gcode(str(prusaslicer_gcode_path))
        assert len(result.hotend_temps) > 0

    def test_hotend_temperature_value_correct(self, prusaslicer_gcode_path: Path):
        # Fixture sets M104 S215 / M109 S215
        result = parse_gcode(str(prusaslicer_gcode_path))
        hotend_values = {cmd.target_temp_c for cmd in result.hotend_temps}
        assert 215.0 in hotend_values

    def test_bed_temperatures_extracted(self, prusaslicer_gcode_path: Path):
        result = parse_gcode(str(prusaslicer_gcode_path))
        assert len(result.bed_temps) > 0

    def test_bed_temperature_value_correct(self, prusaslicer_gcode_path: Path):
        # Fixture sets M140 S60 / M190 S60
        result = parse_gcode(str(prusaslicer_gcode_path))
        bed_values = {cmd.target_temp_c for cmd in result.bed_temps}
        assert 60.0 in bed_values

    def test_print_speed_extracted(self, prusaslicer_gcode_path: Path):
        result = parse_gcode(str(prusaslicer_gcode_path))
        assert result.print_speed_mm_s is not None
        assert result.print_speed_mm_s > 0

    def test_retraction_distance_extracted(self, prusaslicer_gcode_path: Path):
        # Fixture has "G1 E-1.0 F2700 ; retract"
        result = parse_gcode(str(prusaslicer_gcode_path))
        assert result.retraction_distance_mm is not None
        assert result.retraction_distance_mm == pytest.approx(1.0)

    def test_retraction_speed_extracted(self, prusaslicer_gcode_path: Path):
        # F2700 mm/min → 45 mm/s
        result = parse_gcode(str(prusaslicer_gcode_path))
        assert result.retraction_speed_mm_s is not None
        assert result.retraction_speed_mm_s == pytest.approx(45.0)

    def test_layer_height_extracted(self, prusaslicer_gcode_path: Path):
        # Fixture comment: "; layer_height = 0.2"
        result = parse_gcode(str(prusaslicer_gcode_path))
        assert result.layer_height_mm is not None
        assert result.layer_height_mm == pytest.approx(0.2)

    def test_estimated_time_present(self, prusaslicer_gcode_path: Path):
        # Fixture: "; estimated printing time (normal mode) = 1h 30m 0s" → 5400s
        result = parse_gcode(str(prusaslicer_gcode_path))
        assert result.estimated_time_s is not None
        assert result.estimated_time_s == pytest.approx(5400.0)

    def test_filament_estimate_present(self, prusaslicer_gcode_path: Path):
        # Fixture: "; filament used [mm] = 5432.1"
        result = parse_gcode(str(prusaslicer_gcode_path))
        assert result.estimated_filament_mm is not None
        assert result.estimated_filament_mm == pytest.approx(5432.1)

    def test_file_path_populated(self, prusaslicer_gcode_path: Path):
        result = parse_gcode(str(prusaslicer_gcode_path))
        assert result.file_path != ""

    def test_file_size_positive(self, prusaslicer_gcode_path: Path):
        result = parse_gcode(str(prusaslicer_gcode_path))
        assert result.file_size_bytes > 0

    def test_line_count_positive(self, prusaslicer_gcode_path: Path):
        result = parse_gcode(str(prusaslicer_gcode_path))
        assert result.line_count > 0

    def test_print_dimensions_present(self, prusaslicer_gcode_path: Path):
        # Fixture has move commands with X/Y coordinates
        result = parse_gcode(str(prusaslicer_gcode_path))
        assert result.print_dimensions is not None


class TestParseBambuStudio:
    """parse_gcode() correctly extracts all parameters from a BambuStudio file."""

    def test_returns_gcode_analysis_instance(self, bambustudio_gcode_path: Path):
        result = parse_gcode(str(bambustudio_gcode_path))
        assert isinstance(result, GcodeAnalysis)

    def test_slicer_detected_as_bambustudio(self, bambustudio_gcode_path: Path):
        result = parse_gcode(str(bambustudio_gcode_path))
        assert result.slicer is not None
        assert "BambuStudio" in result.slicer

    def test_slicer_version_included(self, bambustudio_gcode_path: Path):
        # Fixture header: "; generated by BambuStudio 1.8.4"
        result = parse_gcode(str(bambustudio_gcode_path))
        assert "1.8.4" in result.slicer

    def test_hotend_temperatures_extracted(self, bambustudio_gcode_path: Path):
        result = parse_gcode(str(bambustudio_gcode_path))
        assert len(result.hotend_temps) > 0

    def test_hotend_temperature_value_correct(self, bambustudio_gcode_path: Path):
        # Fixture sets M104 S220 / M109 S220
        result = parse_gcode(str(bambustudio_gcode_path))
        hotend_values = {cmd.target_temp_c for cmd in result.hotend_temps}
        assert 220.0 in hotend_values

    def test_bed_temperatures_extracted(self, bambustudio_gcode_path: Path):
        result = parse_gcode(str(bambustudio_gcode_path))
        assert len(result.bed_temps) > 0

    def test_bed_temperature_value_correct(self, bambustudio_gcode_path: Path):
        # Fixture sets M140 S55 / M190 S55
        result = parse_gcode(str(bambustudio_gcode_path))
        bed_values = {cmd.target_temp_c for cmd in result.bed_temps}
        assert 55.0 in bed_values

    def test_print_speed_extracted(self, bambustudio_gcode_path: Path):
        result = parse_gcode(str(bambustudio_gcode_path))
        assert result.print_speed_mm_s is not None
        assert result.print_speed_mm_s > 0

    def test_retraction_distance_extracted(self, bambustudio_gcode_path: Path):
        # Fixture has "G1 E-1.0 F2700 ; retract"
        result = parse_gcode(str(bambustudio_gcode_path))
        assert result.retraction_distance_mm is not None
        assert result.retraction_distance_mm == pytest.approx(1.0)

    def test_retraction_speed_extracted(self, bambustudio_gcode_path: Path):
        result = parse_gcode(str(bambustudio_gcode_path))
        assert result.retraction_speed_mm_s is not None
        assert result.retraction_speed_mm_s > 0

    def test_layer_height_extracted(self, bambustudio_gcode_path: Path):
        # Fixture comment: "; layer_height = 0.2"
        result = parse_gcode(str(bambustudio_gcode_path))
        assert result.layer_height_mm is not None
        assert result.layer_height_mm == pytest.approx(0.2)

    def test_estimated_time_present(self, bambustudio_gcode_path: Path):
        # Fixture: "; total estimated time: 5400"
        result = parse_gcode(str(bambustudio_gcode_path))
        assert result.estimated_time_s is not None
        assert result.estimated_time_s == pytest.approx(5400.0)

    def test_filament_estimate_present(self, bambustudio_gcode_path: Path):
        # Fixture: "; filament used [mm] = 5100.0"
        result = parse_gcode(str(bambustudio_gcode_path))
        assert result.estimated_filament_mm is not None
        assert result.estimated_filament_mm == pytest.approx(5100.0)

    def test_print_dimensions_present(self, bambustudio_gcode_path: Path):
        result = parse_gcode(str(bambustudio_gcode_path))
        assert result.print_dimensions is not None


class TestParseOrcaSlicer:
    """parse_gcode() correctly extracts all parameters from an OrcaSlicer file."""

    def test_returns_gcode_analysis_instance(self, orcaslicer_gcode_path: Path):
        result = parse_gcode(str(orcaslicer_gcode_path))
        assert isinstance(result, GcodeAnalysis)

    def test_slicer_detected_as_orcaslicer(self, orcaslicer_gcode_path: Path):
        result = parse_gcode(str(orcaslicer_gcode_path))
        assert result.slicer is not None
        assert "OrcaSlicer" in result.slicer

    def test_slicer_version_included(self, orcaslicer_gcode_path: Path):
        # Fixture header: "; generated by OrcaSlicer 2.0.0"
        result = parse_gcode(str(orcaslicer_gcode_path))
        assert "2.0.0" in result.slicer

    def test_hotend_temperatures_extracted(self, orcaslicer_gcode_path: Path):
        result = parse_gcode(str(orcaslicer_gcode_path))
        assert len(result.hotend_temps) > 0

    def test_hotend_temperature_value_correct(self, orcaslicer_gcode_path: Path):
        # Fixture sets M104 S215 / M109 S215
        result = parse_gcode(str(orcaslicer_gcode_path))
        hotend_values = {cmd.target_temp_c for cmd in result.hotend_temps}
        assert 215.0 in hotend_values

    def test_bed_temperatures_extracted(self, orcaslicer_gcode_path: Path):
        result = parse_gcode(str(orcaslicer_gcode_path))
        assert len(result.bed_temps) > 0

    def test_bed_temperature_value_correct(self, orcaslicer_gcode_path: Path):
        # Fixture sets M140 S60 / M190 S60
        result = parse_gcode(str(orcaslicer_gcode_path))
        bed_values = {cmd.target_temp_c for cmd in result.bed_temps}
        assert 60.0 in bed_values

    def test_print_speed_extracted(self, orcaslicer_gcode_path: Path):
        result = parse_gcode(str(orcaslicer_gcode_path))
        assert result.print_speed_mm_s is not None
        assert result.print_speed_mm_s > 0

    def test_retraction_distance_extracted(self, orcaslicer_gcode_path: Path):
        # Fixture has "G1 E-1.0 F2700 ; retract"
        result = parse_gcode(str(orcaslicer_gcode_path))
        assert result.retraction_distance_mm is not None
        assert result.retraction_distance_mm == pytest.approx(1.0)

    def test_retraction_speed_extracted(self, orcaslicer_gcode_path: Path):
        result = parse_gcode(str(orcaslicer_gcode_path))
        assert result.retraction_speed_mm_s is not None
        assert result.retraction_speed_mm_s > 0

    def test_layer_height_extracted(self, orcaslicer_gcode_path: Path):
        # Fixture comment: "; layer_height = 0.2"
        result = parse_gcode(str(orcaslicer_gcode_path))
        assert result.layer_height_mm is not None
        assert result.layer_height_mm == pytest.approx(0.2)

    def test_estimated_time_present(self, orcaslicer_gcode_path: Path):
        # Fixture: "; total estimated time: 5280"
        result = parse_gcode(str(orcaslicer_gcode_path))
        assert result.estimated_time_s is not None
        assert result.estimated_time_s == pytest.approx(5280.0)

    def test_filament_estimate_present(self, orcaslicer_gcode_path: Path):
        # Fixture: "; filament used [mm] = 5250.5"
        result = parse_gcode(str(orcaslicer_gcode_path))
        assert result.estimated_filament_mm is not None
        assert result.estimated_filament_mm == pytest.approx(5250.5)

    def test_print_dimensions_present(self, orcaslicer_gcode_path: Path):
        result = parse_gcode(str(orcaslicer_gcode_path))
        assert result.print_dimensions is not None


class TestParseCura:
    """parse_gcode() correctly extracts all parameters from a Cura file."""

    def test_returns_gcode_analysis_instance(self, cura_gcode_path: Path):
        result = parse_gcode(str(cura_gcode_path))
        assert isinstance(result, GcodeAnalysis)

    def test_slicer_detected_as_cura(self, cura_gcode_path: Path):
        result = parse_gcode(str(cura_gcode_path))
        assert result.slicer is not None
        assert "Cura" in result.slicer

    def test_slicer_name_is_cura_steam_engine(self, cura_gcode_path: Path):
        # The fixture's first Cura marker is ";FLAVOR:Marlin" on line 1, which
        # matches the flavor pattern (no version group) before the
        # "Generated with Cura_SteamEngine 5.6.0" line on line 5.
        # detect_slicer returns on the first match, so the result is
        # "Cura_SteamEngine" without a version number.
        result = parse_gcode(str(cura_gcode_path))
        assert result.slicer == "Cura_SteamEngine"

    def test_hotend_temperatures_extracted(self, cura_gcode_path: Path):
        result = parse_gcode(str(cura_gcode_path))
        assert len(result.hotend_temps) > 0

    def test_hotend_temperature_value_correct(self, cura_gcode_path: Path):
        # Fixture sets M104 S210 / M109 S210
        result = parse_gcode(str(cura_gcode_path))
        hotend_values = {cmd.target_temp_c for cmd in result.hotend_temps}
        assert 210.0 in hotend_values

    def test_bed_temperatures_extracted(self, cura_gcode_path: Path):
        result = parse_gcode(str(cura_gcode_path))
        assert len(result.bed_temps) > 0

    def test_bed_temperature_value_correct(self, cura_gcode_path: Path):
        # Fixture sets M140 S60 / M190 S60
        result = parse_gcode(str(cura_gcode_path))
        bed_values = {cmd.target_temp_c for cmd in result.bed_temps}
        assert 60.0 in bed_values

    def test_print_speed_extracted(self, cura_gcode_path: Path):
        result = parse_gcode(str(cura_gcode_path))
        assert result.print_speed_mm_s is not None
        assert result.print_speed_mm_s > 0

    def test_retraction_distance_extracted(self, cura_gcode_path: Path):
        # Fixture has "G1 E-1.0 F2700 ; retract"
        result = parse_gcode(str(cura_gcode_path))
        assert result.retraction_distance_mm is not None
        assert result.retraction_distance_mm == pytest.approx(1.0)

    def test_retraction_speed_extracted(self, cura_gcode_path: Path):
        result = parse_gcode(str(cura_gcode_path))
        assert result.retraction_speed_mm_s is not None
        assert result.retraction_speed_mm_s > 0

    def test_layer_height_extracted(self, cura_gcode_path: Path):
        # Fixture comment: ";Layer height: 0.2"
        result = parse_gcode(str(cura_gcode_path))
        assert result.layer_height_mm is not None
        assert result.layer_height_mm == pytest.approx(0.2)

    def test_estimated_time_present(self, cura_gcode_path: Path):
        # Fixture: ";TIME:5400"
        result = parse_gcode(str(cura_gcode_path))
        assert result.estimated_time_s is not None
        assert result.estimated_time_s == pytest.approx(5400.0)

    def test_filament_estimate_present(self, cura_gcode_path: Path):
        # Fixture: ";Filament used: 5.432m" → 5432 mm
        result = parse_gcode(str(cura_gcode_path))
        assert result.estimated_filament_mm is not None
        assert result.estimated_filament_mm == pytest.approx(5432.0)

    def test_print_dimensions_present(self, cura_gcode_path: Path):
        result = parse_gcode(str(cura_gcode_path))
        assert result.print_dimensions is not None


# ---------------------------------------------------------------------------
# T010 — parse_gcode() error cases
# ---------------------------------------------------------------------------


class TestParseGcodeErrorCases:
    """parse_gcode() raises the correct exceptions for invalid inputs."""

    def test_empty_file_raises_gcode_parse_error(self, gcode_fixtures_dir: Path):
        empty_path = gcode_fixtures_dir / "empty.gcode"
        with pytest.raises(GcodeParseError):
            parse_gcode(str(empty_path))

    def test_empty_file_error_message_mentions_empty(self, gcode_fixtures_dir: Path):
        empty_path = gcode_fixtures_dir / "empty.gcode"
        with pytest.raises(GcodeParseError, match="empty"):
            parse_gcode(str(empty_path))

    def test_non_gcode_extension_raises_unsupported_format_error(self, tmp_path: Path):
        stl_path = tmp_path / "model.stl"
        stl_path.write_text("solid fake\nendsolid\n")
        with pytest.raises(UnsupportedFormatError):
            parse_gcode(str(stl_path))

    def test_txt_extension_raises_unsupported_format_error(self, tmp_path: Path):
        txt_path = tmp_path / "notes.txt"
        txt_path.write_text("G28\nM104 S200\n")
        with pytest.raises(UnsupportedFormatError):
            parse_gcode(str(txt_path))

    def test_nonexistent_file_raises_file_not_found(self, tmp_path: Path):
        missing = tmp_path / "does_not_exist.gcode"
        with pytest.raises(FileNotFoundError):
            parse_gcode(str(missing))

    def test_unsupported_format_error_message_mentions_extension(self, tmp_path: Path):
        bad_path = tmp_path / "model.obj"
        bad_path.write_text("v 0 0 0\n")
        with pytest.raises(UnsupportedFormatError, match=r"\.gcode"):
            parse_gcode(str(bad_path))


# ---------------------------------------------------------------------------
# T017 — validate_gcode() status outcome tests
# ---------------------------------------------------------------------------


class TestValidateGcodePassWithPLA:
    """validate_gcode() returns PASS when PLA temps match the PLA profile.

    PrusaSlicer fixture uses 215°C hotend and 60°C bed — both within the
    PLA knowledge-base ranges (190-220°C hotend, 50-70°C bed).
    """

    def test_status_is_pass(self, prusaslicer_gcode_path: Path):
        result = validate_gcode(str(prusaslicer_gcode_path), material="PLA")
        assert result.status == ValidationStatus.PASS

    def test_returns_validation_result_with_material_profile(self, prusaslicer_gcode_path: Path):
        result = validate_gcode(str(prusaslicer_gcode_path), material="PLA")
        assert result.material_profile == "PLA"

    def test_checks_list_is_non_empty(self, prusaslicer_gcode_path: Path):
        result = validate_gcode(str(prusaslicer_gcode_path), material="PLA")
        assert len(result.checks) > 0

    def test_no_failures_present(self, prusaslicer_gcode_path: Path):
        result = validate_gcode(str(prusaslicer_gcode_path), material="PLA")
        assert result.failures == []

    def test_summary_non_empty(self, prusaslicer_gcode_path: Path):
        result = validate_gcode(str(prusaslicer_gcode_path), material="PLA")
        assert result.summary != ""

    def test_gcode_analysis_populated(self, prusaslicer_gcode_path: Path):
        result = validate_gcode(str(prusaslicer_gcode_path), material="PLA")
        assert isinstance(result.gcode_analysis, GcodeAnalysis)
        assert len(result.gcode_analysis.hotend_temps) > 0


class TestValidateGcodeWarnWithPETGTempsOnPLAProfile:
    """validate_gcode() returns WARN when PETG temps (240°C) are used against
    the PLA profile (max 220°C).

    A G-code with a 240°C hotend is above the PLA maximum; the validator
    must flag this as WARN (quality risk, not a physical impossibility).
    """

    @pytest.fixture()
    def petg_temps_gcode(self, tmp_path: Path) -> Path:
        """G-code with PETG-range temperatures (240°C hotend, 80°C bed)."""
        content = (
            "; minimal gcode with PETG temps\n"
            "M104 S240 ; PETG hotend\n"
            "M140 S80 ; PETG bed\n"
            "M190 S80\n"
            "M109 S240\n"
            "G28\n"
            "G1 Z0.2 F3000\n"
            "G1 X10 Y10 E1.0 F1500\n"
            "G1 X50 Y50 E3.0 F1500\n"
            "G1 E-1.0 F2700\n"
            "M107\n"
            "M84\n"
        )
        path = tmp_path / "petg_temps.gcode"
        path.write_text(content)
        return path

    def test_status_is_warn(self, petg_temps_gcode: Path):
        result = validate_gcode(str(petg_temps_gcode), material="PLA")
        assert result.status == ValidationStatus.WARN

    def test_warnings_list_is_non_empty(self, petg_temps_gcode: Path):
        result = validate_gcode(str(petg_temps_gcode), material="PLA")
        # result.warnings contains formatted "[check_name] message" strings
        assert len(result.warnings) > 0

    def test_no_hard_failures_present(self, petg_temps_gcode: Path):
        # Temperature mismatch is advisory (WARN), not a hard FAIL
        result = validate_gcode(str(petg_temps_gcode), material="PLA")
        assert result.failures == []

    def test_hotend_temperature_check_is_warn(self, petg_temps_gcode: Path):
        from print3d_skill.models.validate import CheckCategory, CheckSeverity

        result = validate_gcode(str(petg_temps_gcode), material="PLA")
        hotend_checks = [
            c
            for c in result.checks
            if c.category == CheckCategory.TEMPERATURE and c.name == "hotend_temperature"
        ]
        assert len(hotend_checks) == 1
        assert hotend_checks[0].severity == CheckSeverity.WARN

    def test_recommendation_references_pla_max_temp(self, petg_temps_gcode: Path):
        result = validate_gcode(str(petg_temps_gcode), material="PLA")
        # At least one recommendation should mention lowering to 220°C
        all_recs = " ".join(result.recommendations)
        assert "220" in all_recs


class TestValidateGcodeFailBuildVolumeExceeded:
    """validate_gcode() returns FAIL when print coordinates exceed the printer
    build volume.

    The generic_bowden profile has a 220x220mm footprint.  A G-code that
    moves to X=300 / Y=300 must trigger a hard FAIL on the build_volume check.
    """

    @pytest.fixture()
    def oversized_gcode(self, tmp_path: Path) -> Path:
        """G-code with moves that exceed a 220x220 build volume."""
        content = (
            "; oversized print\n"
            "M104 S215\n"
            "M140 S60\n"
            "M190 S60\n"
            "M109 S215\n"
            "G28\n"
            "G1 Z0.2 F3000\n"
            # Moves to X=300, Y=300 — well outside a 220×220mm bed
            "G1 X0 Y0 E0 F1500\n"
            "G1 X300 Y0 E5.0 F1500\n"
            "G1 X300 Y300 E10.0 F1500\n"
            "G1 X0 Y300 E15.0 F1500\n"
            "G1 X0 Y0 E20.0 F1500\n"
            "G1 E-1.0 F2700\n"
            "M107\n"
            "M84\n"
        )
        path = tmp_path / "oversized.gcode"
        path.write_text(content)
        return path

    def test_status_is_fail(self, oversized_gcode: Path):
        result = validate_gcode(str(oversized_gcode), printer="generic_bowden")
        assert result.status == ValidationStatus.FAIL

    def test_failures_list_is_non_empty(self, oversized_gcode: Path):
        result = validate_gcode(str(oversized_gcode), printer="generic_bowden")
        assert len(result.failures) > 0

    def test_build_volume_check_fails(self, oversized_gcode: Path):
        from print3d_skill.models.validate import CheckCategory, CheckSeverity

        result = validate_gcode(str(oversized_gcode), printer="generic_bowden")
        volume_checks = [
            c
            for c in result.checks
            if c.category == CheckCategory.DIMENSIONS and c.name == "build_volume"
        ]
        assert len(volume_checks) == 1
        assert volume_checks[0].severity == CheckSeverity.FAIL

    def test_failure_message_mentions_build_volume(self, oversized_gcode: Path):
        result = validate_gcode(str(oversized_gcode), printer="generic_bowden")
        all_failures = " ".join(result.failures)
        assert "build_volume" in all_failures

    def test_recommendation_suggests_scaling_down(self, oversized_gcode: Path):
        result = validate_gcode(str(oversized_gcode), printer="generic_bowden")
        all_recs = " ".join(result.recommendations)
        # The check recommendation mentions scaling or larger printer
        assert "scale" in all_recs.lower() or "larger" in all_recs.lower()


class TestValidateMaterialOnlyNoprinter:
    """validate_gcode() with material= only (no printer) runs material checks
    and skips printer-specific checks (retraction, build volume)."""

    def test_status_is_not_error(self, prusaslicer_gcode_path: Path):
        result = validate_gcode(str(prusaslicer_gcode_path), material="PLA")
        assert result.status in (
            ValidationStatus.PASS,
            ValidationStatus.WARN,
            ValidationStatus.FAIL,
        )

    def test_material_profile_recorded(self, prusaslicer_gcode_path: Path):
        result = validate_gcode(str(prusaslicer_gcode_path), material="PLA")
        assert result.material_profile == "PLA"

    def test_printer_profile_is_none(self, prusaslicer_gcode_path: Path):
        result = validate_gcode(str(prusaslicer_gcode_path), material="PLA")
        assert result.printer_profile is None

    def test_no_retraction_check_without_printer(self, prusaslicer_gcode_path: Path):
        # Without a printer profile the retraction_distance check is not run
        result = validate_gcode(str(prusaslicer_gcode_path), material="PLA")
        check_names = {c.name for c in result.checks}
        assert "retraction_distance" not in check_names

    def test_no_build_volume_check_without_printer(self, prusaslicer_gcode_path: Path):
        result = validate_gcode(str(prusaslicer_gcode_path), material="PLA")
        check_names = {c.name for c in result.checks}
        assert "build_volume" not in check_names

    def test_temperature_checks_present(self, prusaslicer_gcode_path: Path):
        from print3d_skill.models.validate import CheckCategory

        result = validate_gcode(str(prusaslicer_gcode_path), material="PLA")
        categories = {c.category for c in result.checks}
        assert CheckCategory.TEMPERATURE in categories


class TestValidatePrinterOnlyNoMaterial:
    """validate_gcode() with printer= only (no material) runs printer-specific
    checks and skips material checks."""

    def test_status_is_not_error(self, prusaslicer_gcode_path: Path):
        result = validate_gcode(str(prusaslicer_gcode_path), printer="generic_bowden")
        assert result.status in (
            ValidationStatus.PASS,
            ValidationStatus.WARN,
            ValidationStatus.FAIL,
        )

    def test_printer_profile_recorded(self, prusaslicer_gcode_path: Path):
        result = validate_gcode(str(prusaslicer_gcode_path), printer="generic_bowden")
        assert result.printer_profile == "generic_bowden"

    def test_material_profile_is_none(self, prusaslicer_gcode_path: Path):
        result = validate_gcode(str(prusaslicer_gcode_path), printer="generic_bowden")
        assert result.material_profile is None

    def test_no_hotend_temperature_check_without_material(self, prusaslicer_gcode_path: Path):
        # Material checks require a material profile
        result = validate_gcode(str(prusaslicer_gcode_path), printer="generic_bowden")
        check_names = {c.name for c in result.checks}
        assert "hotend_temperature" not in check_names

    def test_retraction_check_present_with_printer(self, prusaslicer_gcode_path: Path):
        result = validate_gcode(str(prusaslicer_gcode_path), printer="generic_bowden")
        check_names = {c.name for c in result.checks}
        assert "retraction_distance" in check_names

    def test_build_volume_check_present_with_printer(self, prusaslicer_gcode_path: Path):
        result = validate_gcode(str(prusaslicer_gcode_path), printer="generic_bowden")
        check_names = {c.name for c in result.checks}
        assert "build_volume" in check_names


class TestValidateUnknownMaterial:
    """validate_gcode() with an unknown material name gracefully skips material
    checks and appends a warning to the result instead of raising."""

    def test_does_not_raise(self, prusaslicer_gcode_path: Path):
        # Must not raise — unknown material is a soft failure
        result = validate_gcode(str(prusaslicer_gcode_path), material="UNOBTAINIUM")
        assert result is not None

    def test_status_is_valid_enum_value(self, prusaslicer_gcode_path: Path):
        result = validate_gcode(str(prusaslicer_gcode_path), material="UNOBTAINIUM")
        assert result.status in (
            ValidationStatus.PASS,
            ValidationStatus.WARN,
            ValidationStatus.FAIL,
        )

    def test_warnings_mention_unknown_material(self, prusaslicer_gcode_path: Path):
        result = validate_gcode(str(prusaslicer_gcode_path), material="UNOBTAINIUM")
        all_warnings = " ".join(result.warnings)
        assert "UNOBTAINIUM" in all_warnings

    def test_warning_mentions_skipped(self, prusaslicer_gcode_path: Path):
        result = validate_gcode(str(prusaslicer_gcode_path), material="UNOBTAINIUM")
        all_warnings = " ".join(result.warnings)
        assert "skipped" in all_warnings.lower()

    def test_material_profile_is_none_in_result(self, prusaslicer_gcode_path: Path):
        # No profile was loaded so material_profile field stays None
        result = validate_gcode(str(prusaslicer_gcode_path), material="UNOBTAINIUM")
        assert result.material_profile is None

    def test_no_hotend_temperature_check_run(self, prusaslicer_gcode_path: Path):
        # With no material profile, temperature checks must not run
        result = validate_gcode(str(prusaslicer_gcode_path), material="UNOBTAINIUM")
        check_names = {c.name for c in result.checks}
        assert "hotend_temperature" not in check_names

    def test_time_estimate_check_still_runs(self, prusaslicer_gcode_path: Path):
        # print_time is always checked regardless of profiles
        result = validate_gcode(str(prusaslicer_gcode_path), material="UNOBTAINIUM")
        check_names = {c.name for c in result.checks}
        assert "print_time" in check_names


# ---------------------------------------------------------------------------
# T017 — route("validate", ...) integration test
# ---------------------------------------------------------------------------


class TestRouteValidateMode:
    """route("validate", gcode_path=...) returns a well-formed ModeResponse."""

    def test_route_returns_mode_response(self, prusaslicer_gcode_path: Path):
        from print3d_skill.models.mode import ModeResponse

        response = route("validate", gcode_path=str(prusaslicer_gcode_path), material="PLA")
        assert isinstance(response, ModeResponse)

    def test_response_mode_is_validate(self, prusaslicer_gcode_path: Path):
        response = route("validate", gcode_path=str(prusaslicer_gcode_path), material="PLA")
        assert response.mode == "validate"

    def test_response_status_is_success(self, prusaslicer_gcode_path: Path):
        response = route("validate", gcode_path=str(prusaslicer_gcode_path), material="PLA")
        assert response.status == "success"

    def test_response_data_contains_validation_result(self, prusaslicer_gcode_path: Path):
        from print3d_skill.models.validate import ValidationResult

        response = route("validate", gcode_path=str(prusaslicer_gcode_path), material="PLA")
        assert response.data is not None
        assert "validation_result" in response.data
        assert isinstance(response.data["validation_result"], ValidationResult)

    def test_response_message_is_non_empty_summary(self, prusaslicer_gcode_path: Path):
        response = route("validate", gcode_path=str(prusaslicer_gcode_path), material="PLA")
        assert response.message != ""

    def test_route_without_gcode_path_returns_error_status(self):
        response = route("validate")
        assert response.status == "error"
        assert response.mode == "validate"

    def test_route_with_printer_profile_succeeds(self, prusaslicer_gcode_path: Path):
        response = route(
            "validate",
            gcode_path=str(prusaslicer_gcode_path),
            material="PLA",
            printer="generic_bowden",
        )
        assert response.status == "success"

    def test_route_validation_result_status_is_enum(self, prusaslicer_gcode_path: Path):
        response = route("validate", gcode_path=str(prusaslicer_gcode_path), material="PLA")
        vr = response.data["validation_result"]
        assert isinstance(vr.status, ValidationStatus)
